// <auto-generated />
using System;
using BreakingNewGround.Server.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BreakingNewGround.Server.DAL.Migrations
{
    [DbContext(typeof(MedicinesContext))]
    [Migration("20250608220432_NullableBodyTypeIdAndTypeId")]
    partial class NullableBodyTypeIdAndTypeId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BreakingNewGround.Server.DAL.Data.Medicine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("BodyTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("body_type_id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long?>("TypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("medicines");
                });

            modelBuilder.Entity("BreakingNewGround.Server.DAL.Data.MedicineBodyType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("medicine_body_type");
                });

            modelBuilder.Entity("BreakingNewGround.Server.DAL.Data.MedicineType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("medicine_type");
                });

            modelBuilder.Entity("BreakingNewGround.Server.DAL.Data.Medicine", b =>
                {
                    b.HasOne("BreakingNewGround.Server.DAL.Data.MedicineBodyType", "BodyType")
                        .WithMany()
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BreakingNewGround.Server.DAL.Data.MedicineType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BodyType");

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
