// <auto-generated />
using System;
using BreakingNewGround.Server.DAL.SQLite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BreakingNewGround.Server.DAL.SQLite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("BreakingNewGround.Server.DAL.SQLite.Data.Medicine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("BodyTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("body_type_id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long?>("TypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("medicines");
                });

            modelBuilder.Entity("BreakingNewGround.Server.DAL.SQLite.Data.MedicineBodyType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("medicine_body_type");
                });

            modelBuilder.Entity("BreakingNewGround.Server.DAL.SQLite.Data.MedicineType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("medicine_type");
                });

            modelBuilder.Entity("BreakingNewGround.Server.DAL.SQLite.Views.ExpirationDateIsClose", b =>
                {
                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("expiration_date");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("IsExpired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_expired");

                    b.Property<string>("MedicineBodyType")
                        .HasColumnType("TEXT")
                        .HasColumnName("medicine_body_type");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("medicine_name");

                    b.Property<string>("MedicineType")
                        .HasColumnType("TEXT")
                        .HasColumnName("medicine_type");

                    b.Property<int>("RemainingTimeInMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("remaining_time_in_months");

                    b.ToTable((string)null);

                    b.ToView("expiration_date_is_close", (string)null);
                });

            modelBuilder.Entity("BreakingNewGround.Server.DAL.SQLite.Data.Medicine", b =>
                {
                    b.HasOne("BreakingNewGround.Server.DAL.SQLite.Data.MedicineBodyType", "BodyType")
                        .WithMany()
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BreakingNewGround.Server.DAL.SQLite.Data.MedicineType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BodyType");

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
