<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<SpaRoot>..\breakingnewground.client</SpaRoot>
		<SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
		<SpaProxyServerUrl>https://localhost:51201</SpaProxyServerUrl>
		<OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
		<UserSecretsId>0e7760b9-8545-44ae-a355-534433a495a4</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.DynamicLinq" Version="10.7.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.6.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\breakingnewground.client\breakingnewground.client.esproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Include="..\BreakingNewGround.Server.DAL.AzureSQL\BreakingNewGround.Server.DAL.AzureSQL.csproj" />
		<ProjectReference Include="..\BreakingNewGround.ServiceDefaults\BreakingNewGround.ServiceDefaults.csproj" />
	</ItemGroup>

	<Target Name="PrepublishAngular" BeforeTargets="PrepareForPublish;CopyFilesToPublishDirectory">
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --configuration production" />
		<RemoveDir Directories="$(ProjectDir)wwwroot" />
		<MakeDir Directories="$(ProjectDir)wwwroot" />
		<Exec Command="xcopy &quot;$(SpaRoot)\dist\breakingnewground.client\browser\*&quot; &quot;$(ProjectDir)\wwwroot\&quot; /E /I /Y" />
	</Target>
</Project>